### ISSUE TITLE
Debugging Decision Tree

### ISSUE THREAD

**Issue by protzetter** [creme-ml/creme#165]
Since I had an issue with DecisionTree classifier which was aborting with following error:

RuntimeError: No best split was found

I tried using the debug_one function instead of predict_one, but I get following error at the first step:

AttributeError: 'Leaf' object has no attribute 'class_counts'

**Comment by MaxHalford** [comment]
Good catch, this is something I ignored while focusing on the performance. I'll get it fixed soon and will add some unit tests. Cheers!

**Comment by MaxHalford** [comment]
Fixed in 1ca1eb6.

**Comment by dobinder** [comment]
For me this error still occurs when I call the fit_one function.

I have attached the complete error:

>~/.local/lib/python3.7/site-packages/creme/tree/decision/tree.py in fit_one(self, x, y)
     54 
     55     def fit_one(self, x, y):
---> 56         self.root = self.root.update(x, y)
     57         return self
     58 
 ~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     13             self.left = self.left.update(x, y)
     14             return self
---> 15         self.right = self.right.update(x, y)
     16         return self
     17 
 ~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     11     def update(self, x, y):
     12         if self.split(x):
---> 13             self.left = self.left.update(x, y)
     14             return self
     15         self.right = self.right.update(x, y)
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     13             self.left = self.left.update(x, y)
     14             return self
---> 15         self.right = self.right.update(x, y)
     16         return self
     17 
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     13             self.left = self.left.update(x, y)
     14             return self
---> 15         self.right = self.right.update(x, y)
     16         return self
     17 
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     13             self.left = self.left.update(x, y)
     14             return self
---> 15         self.right = self.right.update(x, y)
     16         return self
     17 
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     13             self.left = self.left.update(x, y)
     14             return self
---> 15         self.right = self.right.update(x, y)
     16         return self
     17 
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     13             self.left = self.left.update(x, y)
     14             return self
---> 15         self.right = self.right.update(x, y)
     16         return self
     17 
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in update(self, x, y)
     71 
     72         # Search for the best split given the current information
---> 73         top_2_diff, split = self.find_best_split()
     74 
     75         # Calculate the Hoeffding 
~/.local/lib/python3.7/site-packages/creme/tree/decision/node.py in find_best_split(self)
    127 
    128         if best_split is None:
--> 129             raise RuntimeError('No best split was found')
    130 
    131         return best_gain - second_best_gain, best_split
RuntimeError: No best split was found

**Comment by MaxHalford** [comment]
Hey @dobinder. Could you provide a reproducible example?

**Comment by dobinder** [comment]
@MaxHalford I can try to. The problem is that I'm working with a quite large non public dataset. So I'm not sure what the best way would be to create a reproducible example. I'll try to reproduce the error with one of the included datasets and put it in here if I can.

What I can tell for now is that I perform a multiclass classification with this model:
tree.DecisionTreeClassifier(max_depth=100,max_bins=60,min_child_samples=2)

**Comment by MaxHalford** [comment]
Actually what you can do before that is to install the latest development version. It's likely that it will fix this bug. You can install with `pip install git+https://github.com/creme-ml/creme --upgrade`. We should making be making a release in around 2 weeks time.
